In [131]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 2C28-A088

 Directory of C:\Users\Mewandi\Desktop\AI_Projects\Job_Recommendation_Engine

08/20/2025  02:17 PM    <DIR>          .
08/20/2025  02:17 PM    <DIR>          ..
08/19/2025  02:04 PM    <DIR>          .ipynb_checkpoints
08/19/2025  12:24 PM            44,428 Cluster Solved.ipynb
08/05/2025  12:58 PM            20,878 education.csv
08/05/2025  12:58 PM           641,984 employment.csv
08/03/2025  11:36 PM           221,690 Explination.jpeg
08/05/2025  12:58 PM           349,053 jobs.csv
08/19/2025  02:05 PM            57,156 MultinomialNB Solved.ipynb
08/20/2025  02:17 PM            41,912 Using CNN.ipynb
               7 File(s)      1,377,101 bytes
               3 Dir(s)  510,506,393,600 bytes free


In [132]:
import numpy as np
import pandas as pd

In [133]:
job_df = pd.read_csv("jobs.csv")

job_df.columns

Index(['jobTitle', 'position', 'minBudget', 'maxBudget', 'travelReq',
       'location', 'description', 'attachment', 'orgId', 'jobType', 'skills',
       'recruiter', 'client', 'minExp', 'maxExp', 'noticePeriod', 'status',
       'jobId', 'createDate', 'vacancies', 'priority', 'priceType', 'workType',
       'comment', 'subvendorId', 'Questionnaires', 'country', 'department',
       'eligibility', 'responsibilities'],
      dtype='object')

In [134]:
100 * job_df.isnull().sum() / len(job_df)

jobTitle              0.000000
position              0.000000
minBudget             0.325733
maxBudget             0.325733
travelReq             0.000000
location              0.000000
description           0.000000
attachment           77.850163
orgId                 0.000000
jobType               0.000000
skills                0.000000
recruiter             0.000000
client                0.000000
minExp                0.000000
maxExp                0.000000
noticePeriod          0.000000
status                0.000000
jobId                 0.000000
createDate            0.000000
vacancies            12.052117
priority             14.657980
priceType            16.286645
workType             15.635179
comment              98.371336
subvendorId         100.000000
Questionnaires      100.000000
country              95.114007
department          100.000000
eligibility         100.000000
responsibilities    100.000000
dtype: float64

#### IDs, duplicates, or any column with >95% missing values

In [135]:
job_df = job_df.drop(columns=['comment'])
job_df = job_df.drop(columns=['subvendorId']) 
job_df = job_df.drop(columns=['Questionnaires']) 
job_df = job_df.drop(columns=['country']) 
job_df = job_df.drop(columns=['department']) 
job_df = job_df.drop(columns=['eligibility']) 
job_df = job_df.drop(columns=['responsibilities']) 
job_df = job_df.drop(columns=['orgId']) 
job_df = job_df.drop(columns=['jobId'])
job_df = job_df.drop(columns=['client'])

In [136]:
job_df.columns

Index(['jobTitle', 'position', 'minBudget', 'maxBudget', 'travelReq',
       'location', 'description', 'attachment', 'jobType', 'skills',
       'recruiter', 'minExp', 'maxExp', 'noticePeriod', 'status', 'createDate',
       'vacancies', 'priority', 'priceType', 'workType'],
      dtype='object')

In [137]:
job_df.head(1)

jobTitle                    position  minBudget  \
0  Plant Maintenance Engineer  Plant Maintenance Engineer   300000.0   

   maxBudget  travelReq     location  \
0   600000.0       True  {Hyderabad}   

                                         description attachment    jobType  \
0  Read and understand the data from P&ID, PEFS, ...        NaN  Permanent   

                  skills recruiter  minExp  maxExp noticePeriod  status  \
0  {"Plant Maintenance"}  DB413862     2.0     5.0   15-30 days  Active   

                  createDate  vacancies priority priceType          workType  
0  2023-01-31 11:09:26.36189        2.0     High       INR  Work from Office

In [138]:
job_df.corr(numeric_only=True)['minBudget']

minBudget    1.000000
maxBudget    0.842138
travelReq    0.092756
minExp       0.038783
maxExp       0.037647
vacancies   -0.007996
Name: minBudget, dtype: float64

In [139]:
job_df.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [140]:
job_col_df = job_df[['jobTitle', 'description', 'status', 'skills']]
#job_col_df

### Employ chossing columns

In [141]:
emp_df = pd.read_csv("employment.csv")

emp_df.columns

Index(['employmentId', 'uploadResume', 'currentCompany', 'currentDesignation',
       'annualSalary', 'industry', 'functionalArea', 'role', 'currentLocation',
       'orgId', 'noticePeriod', 'skills', 'totalWorkExp', 'minExp', 'maxExp',
       'applicantId', 'preferedLocation', 'holdingAnyOffer', 'expectedCtc',
       'feedback', 'comment', 'isCurrent', 'companyEmail', 'packageOffered',
       'lastWorkingDay', 'remarks', 'previousCompany', 'offerLetter',
       'experienceLetter', 'relieveingLetter', 'isRecent', 'paySlips',
       'createdOn'],
      dtype='object')

In [142]:
emp_df = emp_df.drop(columns=['employmentId'])
emp_df = emp_df.drop(columns=['applicantId'])
emp_df = emp_df.drop(columns=['orgId'])

In [143]:
100 * emp_df.isnull().sum() / len(emp_df)

uploadResume           23.773225
currentCompany          4.621248
currentDesignation      2.048595
annualSalary            5.002382
industry                4.525965
functionalArea          5.383516
role                  100.000000
currentLocation         4.764173
noticePeriod            8.575512
skills                  0.000000
totalWorkExp            4.621248
minExp                100.000000
maxExp                100.000000
preferedLocation       26.822296
holdingAnyOffer        27.870414
expectedCtc            26.679371
feedback               98.999524
comment                92.424964
isCurrent              43.163411
companyEmail           66.936636
packageOffered         99.285374
lastWorkingDay         98.999524
remarks                97.189138
previousCompany       100.000000
offerLetter           100.000000
experienceLetter      100.000000
relieveingLetter      100.000000
isRecent              100.000000
paySlips              100.000000
createdOn               0.000000
dtype: flo

In [144]:
emp_df.head(2)

uploadResume                       currentCompany  currentDesignation  \
0          NaN                   ESMOB Technologies  React JS Developer   
1          NaN  Lejara Global IT Solutions Pvt. Ltd       RPA Developer   

  annualSalary  industry      functionalArea  role currentLocation  \
0          3.5       1.0  Software Developer   NaN       Hyderabad   
1          4.5       1.0  Software Developer   NaN       Hyderabad   

  noticePeriod        skills  ...  packageOffered  lastWorkingDay  remarks  \
0          NaN      {css,js}  ...             NaN             NaN      NaN   
1          NaN  {RPA,python}  ...             NaN             NaN      NaN   

  previousCompany offerLetter experienceLetter relieveingLetter isRecent  \
0             NaN         NaN              NaN              NaN      NaN   
1             NaN         NaN              NaN              NaN      NaN   

  paySlips                   createdOn  
0      NaN  2024-03-08 08:49:43.960932  
1      NaN  2024-03-08 08:49:43.960932  

[2 rows x 30 columns]

In [145]:
emp_cols_df = emp_df[['functionalArea', 'skills']]

### Education chossing columns

In [146]:
edu_df = pd.read_csv("education.csv")

edu_df.columns

Index(['Id', 'primarySchool', 'primaryPercentage', 'primaryPassoutYear',
       'secondarySchool', 'secondaryPercentage', 'secondaryPassoutYear',
       'graduation', 'graduationPercentage', 'graduationPassoutYear', 'orgId',
       'applicantId', 'certificates', 'name', 'degree', 'fieldOfStudy',
       'percentage', 'certificate', 'createdOn'],
      dtype='object')

In [147]:
edu_df = edu_df.drop(columns=['Id'])
edu_df = edu_df.drop(columns=['applicantId'])
edu_df = edu_df.drop(columns=['orgId'])

In [148]:
edu_df.head(3)

primarySchool  primaryPercentage  primaryPassoutYear  \
0                NaN                  0                   0   
1  Marks High school                 86                1999   
2                NaN                  0                   0   

     secondarySchool  secondaryPercentage  secondaryPassoutYear graduation  \
0                NaN                  0.0                     0        NaN   
1  Marks High school                 80.0                  2001        NaN   
2                NaN                  0.0                     0        NaN   

   graduationPercentage  graduationPassoutYear certificates  name  degree  \
0                   0.0                      0          NaN   NaN     NaN   
1                   0.0                      0          NaN   NaN     NaN   
2                   0.0                      0          NaN   NaN     NaN   

   fieldOfStudy  percentage  certificate                   createdOn  
0           NaN         NaN          NaN  2024-03-08 08:48:16.349684  
1           NaN         NaN          NaN  2024-03-08 08:48:16.349684  
2           NaN         NaN          NaN  2024-03-08 08:48:16.349684

In [149]:
100 * edu_df.isnull().sum() / len(edu_df)

primarySchool             94.148936
primaryPercentage          0.000000
primaryPassoutYear         0.000000
secondarySchool           95.744681
secondaryPercentage        0.000000
secondaryPassoutYear       0.000000
graduation                95.212766
graduationPercentage       0.000000
graduationPassoutYear      0.000000
certificates              92.021277
name                     100.000000
degree                   100.000000
fieldOfStudy             100.000000
percentage               100.000000
certificate              100.000000
createdOn                  0.000000
dtype: float64

### Let's combine all datas to make one

In [150]:
job_col_df.rename(columns={'skills': 'required_skills'}, inplace=True)
emp_cols_df.rename(columns={'skills': 'employee_skills'}, inplace=True)

C:\Users\Mewandi\AppData\Local\Temp\ipykernel_10160\1312139321.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  job_col_df.rename(columns={'skills': 'required_skills'}, inplace=True)
C:\Users\Mewandi\AppData\Local\Temp\ipykernel_10160\1312139321.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emp_cols_df.rename(columns={'skills': 'employee_skills'}, inplace=True)


In [151]:
total_df = pd.concat([job_col_df, emp_cols_df])

In [152]:
total_df = pd.DataFrame(total_df)

In [153]:
100 * total_df.isnull().sum() / len(total_df)

jobTitle           87.240233
description        87.240233
status             87.240233
required_skills    87.240233
functionalArea     17.456359
employee_skills    12.759767
dtype: float64

In [154]:
for i in total_df:
    total_df[i] = total_df[i].fillna(" ")

In [155]:
100 * total_df.isnull().sum() / len(total_df)

jobTitle           0.0
description        0.0
status             0.0
required_skills    0.0
functionalArea     0.0
employee_skills    0.0
dtype: float64

In [156]:
total_df.head(2)

jobTitle  \
0  Plant Maintenance Engineer   
1   Adobe Analytics developer   

                                         description  status  \
0  Read and understand the data from P&ID, PEFS, ...  Active   
1  An understanding of the marketing technologies...  Active   

                                     required_skills functionalArea  \
0                              {"Plant Maintenance"}                  
1  {"Adobe anaytics",Agile,tableau,Marketo,"power...                  

  employee_skills  
0                  
1

#### Categorical Columns and Text Columns

In [157]:
cate_cols = total_df[['jobTitle', 'status', 'functionalArea']]
text_cols = total_df[['description', 'required_skills', 'employee_skills']]

In [172]:
# text_cols
# cate_cols

In [197]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Embedding, Dense, Conv1D, GlobalMaxPooling1D, LSTM, concatenate, Dropout, Flatten
from tensorflow.keras.models import Model
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


# -------------------- 1. Encode categorical columns --------------------
#enc_jobtitle = LabelEncoder()
#cate_cols['enc_jobtitle'] = enc_jobtitle.fit_transform(cate_cols['jobTitle'].astype(str))
#jobtitle_len = len(cate_cols['enc_jobtitle'])

enc_status = LabelEncoder()
cate_cols['enc_status'] = enc_status.fit_transform(cate_cols['status'].astype(str))
status_len = len(cate_cols['enc_status'])

enc_functional = LabelEncoder()
cate_cols['enc_functionalArea'] = enc_status.fit_transform(cate_cols['functionalArea'].astype(str))
functional_len = len(cate_cols['enc_functionalArea'])


# -------------------- 2. Embedding for categorical columns --------------------
#jobtitle_input = Input(shape=(1,), name='jobTitle')
#jobtitle_emb = Embedding(input_dim=jobtitle_len, output_dim=8)(jobtitle_input)
#jobtitle_emb = Flatten()(jobtitle_emb)

status_input = Input(shape=(1,), name='status')
status_emb = Embedding(input_dim=status_len, output_dim=4)(status_input)
status_emb = Flatten()(status_emb)

functional_input = Input(shape=(1,), name='functionalArea')
functional_emb = Embedding(input_dim=functional_len, output_dim=4)(functional_input)
functional_emb = Flatten()(functional_emb)


# -------------------- 3. Tokenize text columns --------------------
desc_len = len(text_cols['description'])
rs_len = len(text_cols['required_skills'])
es_len = len(text_cols['employee_skills'])

max_len = 500

desc_token = Tokenizer(num_words = desc_len, oov_token = '<OOV>')
desc_token.fit_on_texts(text_cols['description'].astype(str))
desc_seq = pad_sequences(desc_token.texts_to_sequences(text_cols['description'].astype(str)), maxlen=max_len)

rs_token = Tokenizer(num_words = rs_len, oov_token = '<OOV>')
rs_token.fit_on_texts(text_cols['required_skills'].astype(str))
rs_seq = pad_sequences(rs_token.texts_to_sequences(text_cols['required_skills'].astype(str)), maxlen=max_len)

es_token = Tokenizer(num_words = es_len, oov_token = '<OOV>')
es_token.fit_on_texts(text_cols['employee_skills'].astype(str))
es_seq = pad_sequences(es_token.texts_to_sequences(text_cols['employee_skills'].astype(str)), maxlen=max_len)


# -------------------- 4. CNN branch for text --------------------
def cnn_text_branch(name, max_len, text_vocab_size):
    text_input = Input(shape=(max_len,), name=name)
    text_emb = Embedding(input_dim=text_vocab_size, output_dim=50)(text_input)
    text_cov = Conv1D(filters=64, kernel_size=5, activation='relu')(text_emb)
    text_pool = GlobalMaxPooling1D()(text_cov)

    return text_input, text_pool

desc_input, desc_features = cnn_text_branch('description', max_len, desc_len)
rs_input, rs_features = cnn_text_branch('required_skills', max_len, rs_len)
es_input, es_features = cnn_text_branch('employee_skills', max_len, es_len)


# -------------------- 5. Merge all features --------------------
all_features = concatenate([
                functional_emb, status_emb, # jobtitle_emb,
                desc_features, rs_features, es_features
                          ])

dense1 = Dense(128, activation='relu')(all_features)
dropout1 = Dropout(0.3)(dense1)
dense2 = Dense(64, activation='relu')(dropout1)
output  = Dense(10, activation='softmax')(dense2)


# -------------------- 6. Model --------------------
model = Model(
    inputs=[ status_input, functional_input,
             desc_input, rs_input, es_input
           ],

    outputs = output
             )

In [198]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
#model.summary()

In [199]:
pred = model.predict([
    #cate_cols['enc_jobtitle'].values,
    cate_cols['enc_status'].values,
    cate_cols['enc_functionalArea'].values,
    desc_seq,
    rs_seq,
    es_seq
])

print("Prediction probabilities:", pred)
print("Predicted class:", np.argmax(pred))

76/76 ━━━━━━━━━━━━━━━━━━━━ 7s 84ms/step
Prediction probabilities: [[0.09811763 0.09539012 0.1019107  ... 0.1006568  0.10064077 0.10090604]
 [0.09906507 0.0947371  0.10327054 ... 0.1010947  0.101675   0.09994814]
 [0.09824561 0.09612384 0.10241286 ... 0.10086281 0.10176491 0.10078271]
 ...
 [0.09971999 0.09849508 0.10106662 ... 0.09927672 0.09962968 0.10153285]
 [0.09942234 0.0992817  0.10135785 ... 0.0991715  0.09903778 0.10241522]
 [0.09971999 0.09849508 0.10106662 ... 0.09927672 0.09962968 0.10153285]]
Predicted class: 716


In [180]:
predicted_index = np.argmax(pred, axis=1)

y = enc_jobtitle.fit_transform(cate_cols['jobTitle']) 

predicted_jobTitle = enc_jobtitle.inverse_transform(predicted_index)
print("Predicted jobTitle:", predicted_jobTitle[0])

Predicted jobTitle:  Sr.Oracle Cloud Finance Functional Consultant 


## Our own Prediction of the job

In [203]:
data = {
    'Description': ['I understand computer languages and also, I solved many projects in AI and Machine Learning'],
    'Status': ['Active'],
    'Required_Skills': ['computer languages'],
    'FunctionalArea': ['Computer Science'],
    'Employee_Skills': ['I am a programmer and I can do whatever you want'],
}

#******************* Encoding Categorical features ******************
data['enc_sta'] = enc_status.fit_transform(list(map(str, data['Status'])))
data['enc_fun'] = enc_functional.fit_transform(list(map(str, data['FunctionalArea'])))


#******************* Sequence Texts features ******************
max_len = 500

desc_seq = pad_sequences(desc_token.texts_to_sequences(list(map(str, data['Description']))), maxlen=max_len)
req_seq  = pad_sequences(desc_token.texts_to_sequences(list(map(str, data['Required_Skills']))), maxlen=max_len)
emp_seq  = pad_sequences(desc_token.texts_to_sequences(list(map(str, data['Employee_Skills']))), maxlen=max_len)



#*********************** Prediction *********************
y_pred = model.predict([
                        data['enc_sta'],
                        data['enc_fun'],
                        desc_seq,
                        req_seq,
                        emp_seq
])

print("Prediction probabilities:", y_pred)
print("Predicted class:", np.argmax(y_pred))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step
Prediction probabilities: [[0.09497931 0.09416872 0.10142311 0.09903959 0.1024613  0.09985645
  0.10452159 0.1014593  0.10056298 0.10152763]]
Predicted class: 6


In [206]:
max_predicted = np.argmax(y_pred, axis=1)

y = enc_jobtitle.fit_transform(total_df['jobTitle']) 

predicted_Jobtitle = enc_jobtitle.inverse_transform(max_predicted)
print("Predicted jobTitle:", predicted_Jobtitle[0])

Predicted jobTitle:  Technical Systems Analyst 


In [214]:
'''
le = LabelEncoder()
total_df['jobTitle_enc'] = le.fit_transform(total_df['jobTitle'])

print(le.classes_)
'''

"\nle = LabelEncoder()\ntotal_df['jobTitle_enc'] = le.fit_transform(total_df['jobTitle'])\n\nprint(le.classes_)\n"